Repository BetterRTX/BetterRTX-Installer, pull requests merged in 2024-02, with the labels that each got.

#75 Create finnish translation of installer.psd1
  v2/Localized/fi/installer.psd1
Labels: localization

#80 fix: IOBit Copying
  v2/installer.ps1
Labels: bug

#82 upd: IOBit process
  v2/installer.ps1
Labels: enhancement

#83 upd: v2 IOBit process
  v2/installer.ps1
Labels: enhancement

#85 fix: v2 API cache condition
  v2/installer.ps1
Labels: bug
