Repository BetterRTX/BetterRTX-Installer, pull requests merged in 2024-03, with the labels that each got.

#87 fix: v2 pack cache
  v2/installer.ps1
Labels: bug

#88 feat: Drop materials to install
  v2/installer.ps1
Labels: enhancement

#79 Add Minecraft Education Support
  v1/BetterRTX_Installer.ps1
Labels: enhancement, question

#93 feat: Launch button / Individual copy option
  v2/Localized/en-US/installer.psd1
  v2/installer.ps1
Labels: enhancement
