Repository BetterRTX/BetterRTX-Installer, pull requests merged in 2025-04, with the labels that each got.

#134 add: pt-BR translation for v2
  CREDITS.md
  v2/Localized/pt-BR/installer.psd1
Labels: localization

#136 fix: Accept other drive paths / Include bloom in .rtpack
  v2/installer.ps1
Labels: bug

#138 fix: Bedrock Launcher / Portable directory installations
  v2/installer.ps1
Labels: enhancement
